### ISSUE TITLE
Currently not working at all.

### ISSUE THREAD

**Issue by Cederick** [GretchenWeeners/SHiFTLANDS#1]
I tried to use this addon today and it didn't work even with everything set to ENG-US.
Also wondering why it's not using https://shift.gearboxsoftware.com/rewards since it let's you use the coed in a link like: https://shift.gearboxsoftware.com/code_redemptions/72125291-8775-4f97-bb8d-9c47b559376a but I don't know how this would handle platform selection after choosing to redeem a code.

I really hope this awesome addon get's fixed soon!
![Anmerkung 2020-09-02 220830](https://user-images.githubusercontent.com/16303253/92031420-e1450500-ed68-11ea-8b98-e980b6b37fc1.png)

**Comment by Cederick** [comment]
Edit: Also there is no Nintendo Switch option for redeeming codes on borderlands.com

**Comment by GretchenWeeners** [comment]
> 
> 
> I tried to use this addon today and it didn't work even with everything set to ENG-US.
> Also wondering why it's not using https://shift.gearboxsoftware.com/rewards since it let's you use the coed in a link like: https://shift.gearboxsoftware.com/code_redemptions/72125291-8775-4f97-bb8d-9c47b559376a but I don't know how this would handle platform selection after choosing to redeem a code.
> 
> I really hope this awesome addon get's fixed soon!
> ![Anmerkung 2020-09-02 220830](https://user-images.githubusercontent.com/16303253/92031420-e1450500-ed68-11ea-8b98-e980b6b37fc1.png)

Maybe you could have brought this to my attention prior to leaving a bad review? RUDE

**Comment by GretchenWeeners** [comment]
I tested on two different browsers (one wash a fresh vm install) and am not having any issues. Please disable all other extensions to see if something is blocking this from working.
